const UserActionTypes ={
    GOOGLE_SIGN_IN_START : 'GOOGLE_SIGN_IN_START',
    GOOGLE_SIGN_IN_SUCCESS : 'GOOGLE_SIGN_IN_SUCCESS',
    GOOGLE_SIGN_IN_FAILURE : 'GOOGLE_SIGN_IN_FAILURE',
    EMAIL_SIGN_IN_START : 'EMAILT_SIGN_IN_START',
    EMAIL_SIGN_IN_SUCCESS : 'EMAIL_SIGN_IN_SUCCESS',
    EMAIL_SIGN_IN_FAILURE : 'EMAIL_SIGN_IN_FAILURE',
    SET_CURRENT_USER : 'SET_CURRENT_USER'
}
export default UserActionTypes;